import type {Screen,Field} from './resources';
const vinculo:Field={key:'vinculoId',label:'Vínculo',resource:'vinculos',required:true};
const quantidade:Field={key:'quantidadeDias',label:'Quantidade de dias',type:'number',required:true};
const motivo:Field={key:'motivo',label:'Justificativa',type:'textarea'};
export const leaveScreens:Screen[]=[
 {path:'direitos',title:'Direitos adquiridos',description:'Aquisições automáticas e históricas. Informe o prazo concessivo; correções de saldo usam ajustes.',columns:['vinculoId','dataAquisicao','quantidadeDias','origem','prazoConcessivo'],fields:[vinculo,{key:'dataAquisicao',label:'Aquisição',type:'date',required:true},{key:'inicioAquisitivo',label:'Início aquisitivo',type:'date'},{key:'fimAquisitivo',label:'Fim aquisitivo',type:'date'},quantidade,{key:'origem',label:'Origem',options:['AUTOMATICA','IMPORTACAO','AJUSTE_MANUAL'],default:'IMPORTACAO'},{key:'prazoConcessivo',label:'Prazo concessivo',type:'date'},{key:'observacoes',label:'Justificativa / observações',type:'textarea'}]},
 {path:'periodos',title:'Férias e descanso',description:'Programação separada de consumo. Dias corridos são sugeridos; diferenças exigem justificativa.',columns:['vinculo','dataInicio','dataFim','quantidadeDias','status'],fields:[vinculo,{key:'tipo',label:'Tipo',options:['FERIAS','DESCANSO_ESTAGIO'],required:true},{key:'dataInicio',label:'Início',type:'date',required:true},{key:'dataFim',label:'Fim',type:'date',required:true},quantidade,{key:'status',label:'Status',options:['PROGRAMADO','EM_GOZO','CONCLUIDO','CANCELADO'],default:'PROGRAMADO'},motivo,{key:'observacoes',label:'Observações',type:'textarea'}]},
 {path:'consumos',title:'Consumo de descanso',description:'Registre dias efetivamente consumidos e o direito utilizado. Para dividir, crie uma alocação por direito.',columns:['periodo','direito','quantidadeDias','motivo'],fields:[{key:'periodoId',label:'Período',resource:'periodos',required:true},{key:'direitoId',label:'Direito adquirido',resource:'direitos'},quantidade,motivo]},
 {path:'ajustes-descanso',title:'Ajustes de descanso',description:'Créditos e débitos excepcionais, sempre com motivo e autoria.',columns:['vinculoId','tipo','quantidadeDias','motivo'],fields:[vinculo,{key:'tipo',label:'Tipo',options:['CREDITO','DEBITO'],required:true},quantidade,{key:'dataReferencia',label:'Data de referência',type:'date'},{...motivo,required:true}]}
];
